#include "./idt.h"
#include "./isr.h"
#include "./low_kernel.h"
#include "./timer.h"
#include "../driver/screen.h"
#include "../driver/keyboard.h"
#include "../kernel/util.h"

isr_t interrupt_handlers[256] = {0, };

char *exception_messages[] = {
    "Division By Zero",
    "Debug",
    "Non Maskable Interrupt",
    "Breakpoint",
    "Into Detected Overflow",
    "Out of Bounds",
    "Invalid Opcode",
    "No Coprocessor",

    "Double Fault",
    "Coprocessor Segment Overrun",
    "Bad TSS",
    "Segment Not Present",
    "Stack Fault",
    "General Protection Fault",
    "Page Fault",
    "Unknown Interrupt",

    "Coprocessor Fault",
    "Alignment Check",
    "Machine Check",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",

    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved"
};

void isr_install() {
    unsigned char data1;
    unsigned char data2;
    set_idt_gate(0, (u32)isr0);
    set_idt_gate(1, (u32)isr1);
    set_idt_gate(2, (u32)isr2);
    set_idt_gate(3, (u32)isr3);
    set_idt_gate(4, (u32)isr4);
    set_idt_gate(5, (u32)isr5);
    set_idt_gate(6, (u32)isr6);
    set_idt_gate(7, (u32)isr7);
    set_idt_gate(8, (u32)isr8);
    set_idt_gate(9, (u32)isr9);
    set_idt_gate(10, (u32)isr10);
    set_idt_gate(11, (u32)isr11);
    set_idt_gate(12, (u32)isr12);
    set_idt_gate(13, (u32)isr13);
    set_idt_gate(14, (u32)isr14);
    set_idt_gate(15, (u32)isr15);
    set_idt_gate(16, (u32)isr16);
    set_idt_gate(17, (u32)isr17);
    set_idt_gate(18, (u32)isr18);
    set_idt_gate(19, (u32)isr19);
    set_idt_gate(20, (u32)isr20);
    set_idt_gate(21, (u32)isr21);
    set_idt_gate(22, (u32)isr22);
    set_idt_gate(23, (u32)isr23);
    set_idt_gate(24, (u32)isr24);
    set_idt_gate(25, (u32)isr25);
    set_idt_gate(26, (u32)isr26);
    set_idt_gate(27, (u32)isr27);
    set_idt_gate(28, (u32)isr28);
    set_idt_gate(29, (u32)isr29);
    set_idt_gate(30, (u32)isr30);
    set_idt_gate(31, (u32)isr31);
    data1 = port_byte_in(PIC1_DATA);
    data2 = port_byte_in(PIC2_DATA);
    port_byte_out(PIC1_COMMAND, 0x11);
    port_byte_out(PIC2_COMMAND, 0x11);
    port_byte_out(PIC1_DATA, IRQ0);
    port_byte_out(PIC2_DATA, IRQ8);
    port_byte_out(PIC1_DATA, 0x4);
    port_byte_out(PIC2_DATA, 0x2);
    port_byte_out(PIC1_DATA, 0x1);
    port_byte_out(PIC2_DATA, 0x1);
    port_byte_out(PIC1_DATA, data1);
    port_byte_out(PIC2_DATA, data2);
    /* From now, irq number generated by master and slave PIC will be
     * 0x20 to 0x2f.
     */
    set_idt_gate(IRQ0, (u32)irq0);
    set_idt_gate(IRQ1, (u32)irq1);
    set_idt_gate(IRQ2, (u32)irq2);
    set_idt_gate(IRQ3, (u32)irq3);
    set_idt_gate(IRQ4, (u32)irq4);
    set_idt_gate(IRQ5, (u32)irq5);
    set_idt_gate(IRQ6, (u32)irq6);
    set_idt_gate(IRQ7, (u32)irq7);
    set_idt_gate(IRQ8, (u32)irq8);
    set_idt_gate(IRQ9, (u32)irq9);
    set_idt_gate(IRQ10, (u32)irq10);
    set_idt_gate(IRQ11, (u32)irq11);
    set_idt_gate(IRQ12, (u32)irq12);
    set_idt_gate(IRQ13, (u32)irq13);
    set_idt_gate(IRQ14, (u32)irq14);
    set_idt_gate(IRQ15, (u32)irq15);
    set_idt();
}

void irq_install() {
    __asm__ __volatile__(
        "sti"
    );
    init_timer(50);
    init_keyboard();
}

void isr_handler(registers_t r) {
    char s[3];

    int_to_ascii(r.int_no, s);
    print(s);
    print("\n");
    print(exception_messages[r.int_no]);
    print("\n");
}

void registers_interrupt_handler(u8 n, isr_t handler) {
    interrupt_handlers[n] = handler;
}

void irq_handler(registers_t r) {
    isr_t handler;

    /* sends EOI if IRQ received is from child PIC. */
    if ( r.int_no >= IRQ8 ) {
        port_byte_out(PIC2_COMMAND, PIC_EOI);
    }
    port_byte_out(PIC1_COMMAND, PIC_EOI);
    if ( interrupt_handlers[r.int_no] ) {
        handler = interrupt_handlers[r.int_no];
        handler(r);
    }
}

